export const routes = [
  {
    route: "FIN",
    bordersRegex: ["Norway|NOR", "Sweden|SWE"],
    notBordersRegex: ["Nicaragua|NIC", "Panama|PAN"],
    name: {
      common: "Finland",
      official: "Republic of Finland",
      native: {
        fin: { official: "Suomen tasavalta", common: "Suomi" },
        swe: { official: "Republiken Finland", common: "Finland" },
      },
    },
    tld: [".fi"],
    capital: ["Helsinki"],
    altSpellings: [
      "FI",
      "Suomi",
      "Republic of Finland",
      "Suomen tasavalta",
      "Republiken Finland",
    ],
    latlng: [64, 26],
    landlocked: false,
    borders: ["NOR", "SWE", "RUS"],
    _id: "644fd523d944d70002c8d352",
    alpha2Code: "FI",
    alpha3Code: "FIN",
    independent: true,
    status: "officially-assigned",
    unMember: true,
    currencies: { EUR: { name: "Euro", symbol: "€" } },
    idd: { root: "+3", suffixes: ["58"] },
    region: "Europe",
    subregion: "Northern Europe",
    languages: { fin: "Finnish", swe: "Swedish" },
    translations: {
      ces: { official: "Finská republika", common: "Finsko" },
      deu: { official: "Republik Finnland", common: "Finnland" },
      est: { official: "Soome Vabariik", common: "Soome" },
      fin: { official: "Suomen tasavalta", common: "Suomi" },
      fra: { official: "République de Finlande", common: "Finlande" },
      hrv: { official: "Republika Finska", common: "Finska" },
      hun: { official: "Finn Köztársaság", common: "Finnország" },
      ita: { official: "Repubblica di Finlandia", common: "Finlandia" },
      jpn: { official: "フィンランド共和国", common: "フィンランド" },
      kor: { official: "핀란드 공화국", common: "핀란드" },
      nld: { official: "Republiek Finland", common: "Finland" },
      per: { official: "جمهوری فنلاند", common: "فنلاند" },
      pol: { official: "Republika Finlandii", common: "Finlandia" },
      por: { official: "República da Finlândia", common: "Finlândia" },
      rus: { official: "Финляндская Республика", common: "Финляндия" },
      slk: { official: "Fínska republika", common: "Fínsko" },
      spa: { official: "República de Finlandia", common: "Finlandia" },
      swe: { official: "Republiken Finland", common: "Finland" },
      urd: { official: "جمہوریہ فن لینڈ", common: "فن لینڈ" },
      zho: { official: "芬兰共和国", common: "芬兰" },
    },
    area: 338424,
    demonyms: {
      eng: { f: "Finnish", m: "Finnish" },
      fra: { f: "Finlandaise", m: "Finlandais" },
    },
    createdAt: "2023-05-01T15:05:07.792Z",
    updatedAt: "2023-05-01T15:05:07.792Z",
    __v: 0,
  },
  {
    route: "EST",
    bordersRegex: ["Latvia|LVA", "Russia|RUS"],
    notBordersRegex: ["Belize|BLZ", "Guatemala|GTM"],
    name: {
      common: "Estonia",
      official: "Republic of Estonia",
      native: { est: { official: "Eesti Vabariik", common: "Eesti" } },
    },
    tld: [".ee"],
    capital: ["Tallinn"],
    altSpellings: ["EE", "Eesti", "Republic of Estonia", "Eesti Vabariik"],
    latlng: [59, 26],
    landlocked: false,
    borders: ["LVA", "RUS"],
    _id: "644fd523d944d70002c8d350",
    alpha2Code: "EE",
    alpha3Code: "EST",
    independent: true,
    status: "officially-assigned",
    unMember: true,
    currencies: { EUR: { name: "Euro", symbol: "€" } },
    idd: { root: "+3", suffixes: ["72"] },
    region: "Europe",
    subregion: "Northern Europe",
    languages: { est: "Estonian" },
    translations: {
      ces: { official: "Estonská republika", common: "Estonsko" },
      cym: { official: "Gweriniaeth Estonia", common: "Estonia" },
      deu: { official: "Republik Estland", common: "Estland" },
      est: { official: "Eesti Vabariik", common: "Eesti" },
      fin: { official: "Viron tasavalta", common: "Viro" },
      fra: { official: "République d'Estonie", common: "Estonie" },
      hrv: { official: "Republika Estonija", common: "Estonija" },
      hun: { official: "Észt Köztársaság", common: "Észtország" },
      ita: { official: "Repubblica di Estonia", common: "Estonia" },
      jpn: { official: "エストニア共和国", common: "エストニア" },
      kor: { official: "에스토니아 공화국", common: "에스토니아" },
      nld: { official: "Republiek Estland", common: "Estland" },
      per: { official: "جمهوری استونی", common: "اِستونی" },
      pol: { official: "Republika Estońska", common: "Estonia" },
      por: { official: "República da Estónia", common: "Estónia" },
      rus: { official: "Эстонская Республика", common: "Эстония" },
      slk: { official: "Estónska republika", common: "Estónsko" },
      spa: { official: "República de Estonia", common: "Estonia" },
      swe: { official: "Republiken Estland", common: "Estland" },
      urd: { official: "جمہوریہ اسٹونیا", common: "اسٹونیا" },
      zho: { official: "爱沙尼亚共和国", common: "爱沙尼亚" },
    },
    area: 45227,
    demonyms: {
      eng: { f: "Estonian", m: "Estonian" },
      fra: { f: "Estonienne", m: "Estonien" },
    },
    createdAt: "2023-05-01T15:05:07.792Z",
    updatedAt: "2023-05-01T15:05:07.792Z",
    __v: 0,
  },
  {
    route: "MEX",
    bordersRegex: ["Belize|BLZ", "Guatemala|GTM"],
    notBordersRegex: ["Latvia|LVA", "Russia|RUS"],
    name: {
      common: "Mexico",
      official: "United Mexican States",
      native: {
        spa: { official: "Estados Unidos Mexicanos", common: "México" },
      },
    },
    tld: [".mx"],
    capital: ["Mexico City"],
    altSpellings: [
      "MX",
      "Mexicanos",
      "United Mexican States",
      "Estados Unidos Mexicanos",
    ],
    latlng: [23, -102],
    landlocked: false,
    borders: ["BLZ", "GTM", "USA"],
    _id: "644fd2288127c7000291e391",
    alpha2Code: "MX",
    alpha3Code: "MEX",
    independent: true,
    status: "officially-assigned",
    unMember: true,
    currencies: { MXN: { name: "Mexican peso", symbol: "$" } },
    idd: { root: "+5", suffixes: ["2"] },
    region: "Americas",
    subregion: "North America",
    languages: { spa: "Spanish" },
    translations: {
      ces: { official: "Spojené státy mexické", common: "Mexiko" },
      deu: { official: "Vereinigte Mexikanische Staaten", common: "Mexiko" },
      est: { official: "Mehhiko Ühendriigid", common: "Mehhiko" },
      fin: { official: "Meksikon yhdysvallat", common: "Meksiko" },
      fra: { official: "États-Unis du Mexique", common: "Mexique" },
      hrv: { official: "Sjedinjene Meksičke Države", common: "Meksiko" },
      hun: { official: "Mexikói Egyesült Államok", common: "Mexikó" },
      ita: { official: "Stati Uniti del Messico", common: "Messico" },
      jpn: { official: "メキシコ合衆国", common: "メキシコ" },
      kor: { official: "멕시코 합중국", common: "멕시코" },
      nld: { official: "Verenigde Mexicaanse Staten", common: "Mexico" },
      per: { official: "ایالات متحد مکزیک", common: "مکزیک" },
      pol: { official: "Meksykańskie Stany Zjednoczone", common: "Meksyk" },
      por: { official: "Estados Unidos Mexicanos", common: "México" },
      rus: { official: "Мексиканские Соединённые Штаты", common: "Мексика" },
      slk: { official: "Spojené štášy mexické", common: "Mexiko" },
      spa: { official: "Estados Unidos Mexicanos", common: "México" },
      swe: { official: "Mexikos förenta stater", common: "Mexiko" },
      urd: { official: "ریاستہائے متحدہ میکسیکو", common: "میکسیکو" },
      zho: { official: "墨西哥合众国", common: "墨西哥" },
    },
    area: 1964375,
    demonyms: {
      eng: { f: "Mexican", m: "Mexican" },
      fra: { f: "Mexicaine", m: "Mexicain" },
    },
    createdAt: "2023-05-01T14:52:24.637Z",
    updatedAt: "2023-05-01T14:52:24.637Z",
    __v: 0,
  },
  {
    route: "CRI",
    bordersRegex: ["Nicaragua|NIC", "Panama|PAN"],
    notBordersRegex: ["Latvia|LVA", "Russia|RUS"],
    name: {
      common: "Costa Rica",
      official: "Republic of Costa Rica",
      native: {
        spa: { official: "República de Costa Rica", common: "Costa Rica" },
      },
    },
    tld: [".cr"],
    capital: ["San José"],
    altSpellings: ["CR", "Republic of Costa Rica", "República de Costa Rica"],
    latlng: [10, -84],
    landlocked: false,
    borders: ["NIC", "PAN"],
    _id: "644fd2288127c7000291e336",
    alpha2Code: "CR",
    alpha3Code: "CRI",
    independent: true,
    status: "officially-assigned",
    unMember: true,
    currencies: { CRC: { name: "Costa Rican colón", symbol: "₡" } },
    idd: { root: "+5", suffixes: ["06"] },
    region: "Americas",
    subregion: "Central America",
    languages: { spa: "Spanish" },
    translations: {
      ces: { official: "Kostarická republika", common: "Kostarika" },
      cym: { official: "Gweriniaeth Costa Rica", common: "Costa Rica" },
      deu: { official: "Republik Costa Rica", common: "Costa Rica" },
      est: { official: "Costa Rica Vabariik", common: "Costa Rica" },
      fin: { official: "Costa Rican tasavalta", common: "Costa Rica" },
      fra: { official: "République du Costa Rica", common: "Costa Rica" },
      hrv: { official: "Republika Kostarika", common: "Kostarika" },
      hun: { official: "Costa Rica-i Köztársaság", common: "Costa Rica" },
      ita: { official: "Repubblica di Costa Rica", common: "Costa Rica" },
      jpn: { official: "コスタリカ共和国", common: "コスタリカ" },
      kor: { official: "코스타리카 공화국", common: "코스타리카" },
      nld: { official: "Republiek Costa Rica", common: "Costa Rica" },
      per: { official: "جمهوری کاستاریکا", common: "کاستاریکا" },
      pol: { official: "Republika Kostaryki", common: "Kostaryka" },
      por: { official: "República da Costa Rica", common: "Costa Rica" },
      rus: { official: "Республика Коста-Рика", common: "Коста-Рика" },
      slk: { official: "Kostarická republika", common: "Kostarika" },
      spa: { official: "República de Costa Rica", common: "Costa Rica" },
      swe: { official: "Republiken Costa Rica", common: "Costa Rica" },
      urd: { official: "جمہوریہ کوسٹاریکا", common: "کوسٹاریکا" },
      zho: { official: "哥斯达黎加共和国", common: "哥斯达黎加" },
    },
    area: 51100,
    demonyms: {
      eng: { f: "Costa Rican", m: "Costa Rican" },
      fra: { f: "Costaricaine", m: "Costaricain" },
    },
    createdAt: "2023-05-01T14:52:24.634Z",
    updatedAt: "2023-05-01T14:52:24.634Z",
    __v: 0,
  },
];

export const old_routes = [
  {
    route: "FIN",
    borders: ["Norway|NOR", "Sweden|SWE"],
    notBorders: ["Nicaragua|NIC", "Panama|PAN"],
    capital: ["Helsinki"],
    _id: "644ef68fab150c0002c9aa73",
    alpha2Code: "FI",
    alpha3Code: "FIN",
    area: 338424,
    name: {
      common: "Finland",
      official: "Republic of Finland",
    },
  },
  {
    route: "EST",
    borders: ["Latvia|LVA", "Russia|RUS"],
    notBorders: ["Belize|BLZ", "Guatemala|GTM"],
    capital: ["Tallinn"],
    _id: "644ef68fab150c0002c9aa71",
    alpha2Code: "EE",
    alpha3Code: "EST",
    area: 45227,
    name: {
      common: "Estonia",
      official: "Republic of Estonia",
    },
  },
  {
    route: "MEX",
    borders: ["Belize|BLZ", "Guatemala|GTM"],
    notBorders: ["Latvia|LVA", "Russia|RUS"],
    capital: ["Mexico City"],
    _id: "644ef68fab150c0002c9aaba",
    alpha2Code: "MX",
    alpha3Code: "MEX",
    name: {
      common: "Mexico",
      official: "United Mexican States",
    },
    area: 1964375,
  },
  {
    route: "CRI",
    borders: ["Nicaragua|NIC", "Panama|PAN"],
    notBorders: ["Latvia|LVA", "Russia|RUS"],
    capital: ["San José"],
    _id: "644ef68fab150c0002c9aa5f",
    alpha2Code: "CR",
    alpha3Code: "CRI",
    name: {
      common: "Costa Rica",
      official: "Republic of Costa Rica",
    },
    area: 51100,
  },
];

export const countries = [
  {
    _id: "644ef14398cd050002edc72b",
    name: { common: "Suriname", official: "Republic of Suriname" },
    alpha2Code: "SR",
    alpha3Code: "SUR",
  },
  {
    _id: "644ef14398cd050002edc72e",
    name: { common: "Sweden", official: "Kingdom of Sweden" },
    alpha2Code: "SE",
    alpha3Code: "SWE",
  },
  {
    _id: "644ef14398cd050002edc72f",
    name: { common: "Eswatini", official: "Kingdom of Eswatini" },
    alpha2Code: "SZ",
    alpha3Code: "SWZ",
  },
  {
    _id: "644ef14398cd050002edc72c",
    name: { common: "Slovakia", official: "Slovak Republic" },
    alpha2Code: "SK",
    alpha3Code: "SVK",
  },
  {
    _id: "644ef14398cd050002edc72d",
    name: { common: "Slovenia", official: "Republic of Slovenia" },
    alpha2Code: "SI",
    alpha3Code: "SVN",
  },
  {
    _id: "644ef14398cd050002edc730",
    name: { common: "Sint Maarten", official: "Sint Maarten" },
    alpha2Code: "SX",
    alpha3Code: "SXM",
  },
  {
    _id: "644ef14398cd050002edc731",
    name: { common: "Seychelles", official: "Republic of Seychelles" },
    alpha2Code: "SC",
    alpha3Code: "SYC",
  },
  {
    _id: "644ef14398cd050002edc732",
    name: { common: "Syria", official: "Syrian Arab Republic" },
    alpha2Code: "SY",
    alpha3Code: "SYR",
  },
  {
    _id: "644ef14398cd050002edc733",
    name: {
      common: "Turks and Caicos Islands",
      official: "Turks and Caicos Islands",
    },
    alpha2Code: "TC",
    alpha3Code: "TCA",
  },
  {
    _id: "644ef14398cd050002edc734",
    name: { common: "Chad", official: "Republic of Chad" },
    alpha2Code: "TD",
    alpha3Code: "TCD",
  },
  {
    _id: "644ef14398cd050002edc735",
    name: { common: "Togo", official: "Togolese Republic" },
    alpha2Code: "TG",
    alpha3Code: "TGO",
  },
  {
    _id: "644ef14398cd050002edc736",
    name: { common: "Thailand", official: "Kingdom of Thailand" },
    alpha2Code: "TH",
    alpha3Code: "THA",
  },
  {
    _id: "644ef14398cd050002edc737",
    name: { common: "Tajikistan", official: "Republic of Tajikistan" },
    alpha2Code: "TJ",
    alpha3Code: "TJK",
  },
  {
    _id: "644ef14398cd050002edc739",
    name: { common: "Turkmenistan", official: "Turkmenistan" },
    alpha2Code: "TM",
    alpha3Code: "TKM",
  },
  {
    _id: "644ef14398cd050002edc738",
    name: { common: "Tokelau", official: "Tokelau" },
    alpha2Code: "TK",
    alpha3Code: "TKL",
  },
  {
    _id: "644ef14398cd050002edc73d",
    name: { common: "Tunisia", official: "Tunisian Republic" },
    alpha2Code: "TN",
    alpha3Code: "TUN",
  },
  {
    _id: "644ef14398cd050002edc73a",
    name: {
      common: "Timor-Leste",
      official: "Democratic Republic of Timor-Leste",
    },
    alpha2Code: "TL",
    alpha3Code: "TLS",
  },
  {
    _id: "644ef14398cd050002edc73e",
    name: { common: "Turkey", official: "Republic of Turkey" },
    alpha2Code: "TR",
    alpha3Code: "TUR",
  },
  {
    _id: "644ef14398cd050002edc73b",
    name: { common: "Tonga", official: "Kingdom of Tonga" },
    alpha2Code: "TO",
    alpha3Code: "TON",
  },
  {
    _id: "644ef14398cd050002edc73c",
    name: {
      common: "Trinidad and Tobago",
      official: "Republic of Trinidad and Tobago",
    },
    alpha2Code: "TT",
    alpha3Code: "TTO",
  },
  {
    _id: "644ef14398cd050002edc73f",
    name: { common: "Tuvalu", official: "Tuvalu" },
    alpha2Code: "TV",
    alpha3Code: "TUV",
  },
  {
    _id: "644ef14398cd050002edc740",
    name: { common: "Taiwan", official: "Republic of China (Taiwan)" },
    alpha2Code: "TW",
    alpha3Code: "TWN",
  },
  {
    _id: "644ef14398cd050002edc741",
    name: { common: "Tanzania", official: "United Republic of Tanzania" },
    alpha2Code: "TZ",
    alpha3Code: "TZA",
  },
  {
    _id: "644ef14398cd050002edc742",
    name: { common: "Uganda", official: "Republic of Uganda" },
    alpha2Code: "UG",
    alpha3Code: "UGA",
  },
  {
    _id: "644ef14398cd050002edc743",
    name: { common: "Ukraine", official: "Ukraine" },
    alpha2Code: "UA",
    alpha3Code: "UKR",
  },
  {
    _id: "644ef14398cd050002edc744",
    name: {
      common: "United States Minor Outlying Islands",
      official: "United States Minor Outlying Islands",
    },
    alpha2Code: "UM",
    alpha3Code: "UMI",
  },
  {
    _id: "644ef14398cd050002edc745",
    name: { common: "Uruguay", official: "Oriental Republic of Uruguay" },
    alpha2Code: "UY",
    alpha3Code: "URY",
  },
  {
    _id: "644ef14398cd050002edc746",
    name: {
      common: "United States",
      official: "United States of America",
    },
    alpha2Code: "US",
    alpha3Code: "USA",
  },
  {
    _id: "644ef14398cd050002edc748",
    name: { common: "Vatican City", official: "Vatican City State" },
    alpha2Code: "VA",
    alpha3Code: "VAT",
  },
  {
    _id: "644ef14398cd050002edc747",
    name: { common: "Uzbekistan", official: "Republic of Uzbekistan" },
    alpha2Code: "UZ",
    alpha3Code: "UZB",
  },
  {
    _id: "644ef14398cd050002edc749",
    name: {
      common: "Saint Vincent and the Grenadines",
      official: "Saint Vincent and the Grenadines",
    },
    alpha2Code: "VC",
    alpha3Code: "VCT",
  },
  {
    _id: "644ef14398cd050002edc74a",
    name: {
      common: "Venezuela",
      official: "Bolivarian Republic of Venezuela",
    },
    alpha2Code: "VE",
    alpha3Code: "VEN",
  },
  {
    _id: "644ef14398cd050002edc74b",
    name: {
      common: "British Virgin Islands",
      official: "Virgin Islands",
    },
    alpha2Code: "VG",
    alpha3Code: "VGB",
  },
  {
    _id: "644ef14398cd050002edc74c",
    name: {
      common: "United States Virgin Islands",
      official: "Virgin Islands of the United States",
    },
    alpha2Code: "VI",
    alpha3Code: "VIR",
  },
  {
    _id: "644ef14398cd050002edc74e",
    name: { common: "Vanuatu", official: "Republic of Vanuatu" },
    alpha2Code: "VU",
    alpha3Code: "VUT",
  },
  {
    _id: "644ef14398cd050002edc74d",
    name: {
      common: "Vietnam",
      official: "Socialist Republic of Vietnam",
    },
    alpha2Code: "VN",
    alpha3Code: "VNM",
  },
  {
    _id: "644ef14398cd050002edc74f",
    name: {
      common: "Wallis and Futuna",
      official: "Territory of the Wallis and Futuna Islands",
    },
    alpha2Code: "WF",
    alpha3Code: "WLF",
  },
  {
    _id: "644ef14398cd050002edc750",
    name: { common: "Samoa", official: "Independent State of Samoa" },
    alpha2Code: "WS",
    alpha3Code: "WSM",
  },
  {
    _id: "644ef14398cd050002edc752",
    name: {
      common: "South Africa",
      official: "Republic of South Africa",
    },
    alpha2Code: "ZA",
    alpha3Code: "ZAF",
  },
  {
    _id: "644ef14398cd050002edc753",
    name: { common: "Zambia", official: "Republic of Zambia" },
    alpha2Code: "ZM",
    alpha3Code: "ZMB",
  },
  {
    _id: "644ef14398cd050002edc751",
    name: { common: "Yemen", official: "Republic of Yemen" },
    alpha2Code: "YE",
    alpha3Code: "YEM",
  },
  {
    _id: "644ef14398cd050002edc754",
    name: { common: "Zimbabwe", official: "Republic of Zimbabwe" },
    alpha2Code: "ZW",
    alpha3Code: "ZWE",
  },
  {
    _id: "644ef14398cd050002edc701",
    name: { common: "Nicaragua", official: "Republic of Nicaragua" },
    alpha2Code: "NI",
    alpha3Code: "NIC",
  },
  {
    _id: "644ef14398cd050002edc704",
    name: { common: "Norway", official: "Kingdom of Norway" },
    alpha2Code: "NO",
    alpha3Code: "NOR",
  },
  {
    _id: "644ef14398cd050002edc707",
    name: { common: "New Zealand", official: "New Zealand" },
    alpha2Code: "NZ",
    alpha3Code: "NZL",
  },
  {
    _id: "644ef14398cd050002edc706",
    name: { common: "Nauru", official: "Republic of Nauru" },
    alpha2Code: "NR",
    alpha3Code: "NRU",
  },
  {
    _id: "644ef14398cd050002edc703",
    name: {
      common: "Netherlands",
      official: "Kingdom of the Netherlands",
    },
    alpha2Code: "NL",
    alpha3Code: "NLD",
  },
  {
    _id: "644ef14398cd050002edc708",
    name: { common: "Oman", official: "Sultanate of Oman" },
    alpha2Code: "OM",
    alpha3Code: "OMN",
  },
  {
    _id: "644ef14398cd050002edc702",
    name: { common: "Niue", official: "Niue" },
    alpha2Code: "NU",
    alpha3Code: "NIU",
  },
  {
    _id: "644ef14398cd050002edc709",
    name: {
      common: "Pakistan",
      official: "Islamic Republic of Pakistan",
    },
    alpha2Code: "PK",
    alpha3Code: "PAK",
  },
  {
    _id: "644ef14398cd050002edc705",
    name: {
      common: "Nepal",
      official: "Federal Democratic Republic of Nepal",
    },
    alpha2Code: "NP",
    alpha3Code: "NPL",
  },
  {
    _id: "644ef14398cd050002edc70a",
    name: { common: "Panama", official: "Republic of Panama" },
    alpha2Code: "PA",
    alpha3Code: "PAN",
  },
  {
    _id: "644ef14398cd050002edc70b",
    name: {
      common: "Pitcairn Islands",
      official: "Pitcairn Group of Islands",
    },
    alpha2Code: "PN",
    alpha3Code: "PCN",
  },
  {
    _id: "644ef14398cd050002edc711",
    name: {
      common: "Puerto Rico",
      official: "Commonwealth of Puerto Rico",
    },
    alpha2Code: "PR",
    alpha3Code: "PRI",
  },
  {
    _id: "644ef14398cd050002edc710",
    name: { common: "Poland", official: "Republic of Poland" },
    alpha2Code: "PL",
    alpha3Code: "POL",
  },
  {
    _id: "644ef14398cd050002edc70d",
    name: {
      common: "Philippines",
      official: "Republic of the Philippines",
    },
    alpha2Code: "PH",
    alpha3Code: "PHL",
  },
  {
    _id: "644ef14398cd050002edc70e",
    name: { common: "Palau", official: "Republic of Palau" },
    alpha2Code: "PW",
    alpha3Code: "PLW",
  },
  {
    _id: "644ef14398cd050002edc70c",
    name: { common: "Peru", official: "Republic of Peru" },
    alpha2Code: "PE",
    alpha3Code: "PER",
  },
  {
    _id: "644ef14398cd050002edc70f",
    name: {
      common: "Papua New Guinea",
      official: "Independent State of Papua New Guinea",
    },
    alpha2Code: "PG",
    alpha3Code: "PNG",
  },
  {
    _id: "644ef14398cd050002edc712",
    name: {
      common: "North Korea",
      official: "Democratic People's Republic of Korea",
    },
    alpha2Code: "KP",
    alpha3Code: "PRK",
  },
  {
    _id: "644ef14398cd050002edc713",
    name: { common: "Portugal", official: "Portuguese Republic" },
    alpha2Code: "PT",
    alpha3Code: "PRT",
  },
  {
    _id: "644ef14398cd050002edc714",
    name: { common: "Paraguay", official: "Republic of Paraguay" },
    alpha2Code: "PY",
    alpha3Code: "PRY",
  },
  {
    _id: "644ef14398cd050002edc715",
    name: { common: "Palestine", official: "State of Palestine" },
    alpha2Code: "PS",
    alpha3Code: "PSE",
  },
  {
    _id: "644ef14398cd050002edc716",
    name: { common: "French Polynesia", official: "French Polynesia" },
    alpha2Code: "PF",
    alpha3Code: "PYF",
  },
  {
    _id: "644ef14398cd050002edc718",
    name: { common: "Réunion", official: "Réunion Island" },
    alpha2Code: "RE",
    alpha3Code: "REU",
  },
  {
    _id: "644ef14398cd050002edc717",
    name: { common: "Qatar", official: "State of Qatar" },
    alpha2Code: "QA",
    alpha3Code: "QAT",
  },
  {
    _id: "644ef14398cd050002edc719",
    name: { common: "Romania", official: "Romania" },
    alpha2Code: "RO",
    alpha3Code: "ROU",
  },
  {
    _id: "644ef14398cd050002edc71a",
    name: { common: "Russia", official: "Russian Federation" },
    alpha2Code: "RU",
    alpha3Code: "RUS",
  },
  {
    _id: "644ef14398cd050002edc71c",
    name: { common: "Saudi Arabia", official: "Kingdom of Saudi Arabia" },
    alpha2Code: "SA",
    alpha3Code: "SAU",
  },
  {
    _id: "644ef14398cd050002edc71b",
    name: { common: "Rwanda", official: "Republic of Rwanda" },
    alpha2Code: "RW",
    alpha3Code: "RWA",
  },
  {
    _id: "644ef14398cd050002edc71e",
    name: { common: "Senegal", official: "Republic of Senegal" },
    alpha2Code: "SN",
    alpha3Code: "SEN",
  },
  {
    _id: "644ef14398cd050002edc71d",
    name: { common: "Sudan", official: "Republic of the Sudan" },
    alpha2Code: "SD",
    alpha3Code: "SDN",
  },
  {
    _id: "644ef14398cd050002edc71f",
    name: { common: "Singapore", official: "Republic of Singapore" },
    alpha2Code: "SG",
    alpha3Code: "SGP",
  },
  {
    _id: "644ef14398cd050002edc720",
    name: {
      common: "South Georgia",
      official: "South Georgia and the South Sandwich Islands",
    },
    alpha2Code: "GS",
    alpha3Code: "SGS",
  },
  {
    _id: "644ef14398cd050002edc722",
    name: { common: "Solomon Islands", official: "Solomon Islands" },
    alpha2Code: "SB",
    alpha3Code: "SLB",
  },
  {
    _id: "644ef14398cd050002edc721",
    name: {
      common: "Svalbard and Jan Mayen",
      official: "Svalbard og Jan Mayen",
    },
    alpha2Code: "SJ",
    alpha3Code: "SJM",
  },
  {
    _id: "644ef14398cd050002edc723",
    name: {
      common: "Sierra Leone",
      official: "Republic of Sierra Leone",
    },
    alpha2Code: "SL",
    alpha3Code: "SLE",
  },
  {
    _id: "644ef14398cd050002edc724",
    name: { common: "El Salvador", official: "Republic of El Salvador" },
    alpha2Code: "SV",
    alpha3Code: "SLV",
  },
  {
    _id: "644ef14398cd050002edc725",
    name: {
      common: "San Marino",
      official: "Most Serene Republic of San Marino",
    },
    alpha2Code: "SM",
    alpha3Code: "SMR",
  },
  {
    _id: "644ef14398cd050002edc726",
    name: { common: "Somalia", official: "Federal Republic of Somalia" },
    alpha2Code: "SO",
    alpha3Code: "SOM",
  },
  {
    _id: "644ef14398cd050002edc727",
    name: {
      common: "Saint Pierre and Miquelon",
      official: "Saint Pierre and Miquelon",
    },
    alpha2Code: "PM",
    alpha3Code: "SPM",
  },
  {
    _id: "644ef14398cd050002edc728",
    name: { common: "Serbia", official: "Republic of Serbia" },
    alpha2Code: "RS",
    alpha3Code: "SRB",
  },
  {
    _id: "644ef14398cd050002edc729",
    name: { common: "South Sudan", official: "Republic of South Sudan" },
    alpha2Code: "SS",
    alpha3Code: "SSD",
  },
  {
    _id: "644ef14398cd050002edc72a",
    name: {
      common: "São Tomé and Príncipe",
      official: "Democratic Republic of São Tomé and Príncipe",
    },
    alpha2Code: "ST",
    alpha3Code: "STP",
  },
  {
    _id: "644ef14398cd050002edc6da",
    name: { common: "Lebanon", official: "Lebanese Republic" },
    alpha2Code: "LB",
    alpha3Code: "LBN",
  },
  {
    _id: "644ef14398cd050002edc6d8",
    name: { common: "Kuwait", official: "State of Kuwait" },
    alpha2Code: "KW",
    alpha3Code: "KWT",
  },
  {
    _id: "644ef14398cd050002edc6d9",
    name: {
      common: "Laos",
      official: "Lao People's Democratic Republic",
    },
    alpha2Code: "LA",
    alpha3Code: "LAO",
  },
  {
    _id: "644ef14398cd050002edc6db",
    name: { common: "Liberia", official: "Republic of Liberia" },
    alpha2Code: "LR",
    alpha3Code: "LBR",
  },
  {
    _id: "644ef14398cd050002edc6dd",
    name: { common: "Saint Lucia", official: "Saint Lucia" },
    alpha2Code: "LC",
    alpha3Code: "LCA",
  },
  {
    _id: "644ef14398cd050002edc6dc",
    name: { common: "Libya", official: "State of Libya" },
    alpha2Code: "LY",
    alpha3Code: "LBY",
  },
  {
    _id: "644ef14398cd050002edc6de",
    name: {
      common: "Liechtenstein",
      official: "Principality of Liechtenstein",
    },
    alpha2Code: "LI",
    alpha3Code: "LIE",
  },
  {
    _id: "644ef14398cd050002edc6df",
    name: {
      common: "Sri Lanka",
      official: "Democratic Socialist Republic of Sri Lanka",
    },
    alpha2Code: "LK",
    alpha3Code: "LKA",
  },
  {
    _id: "644ef14398cd050002edc6e0",
    name: { common: "Lesotho", official: "Kingdom of Lesotho" },
    alpha2Code: "LS",
    alpha3Code: "LSO",
  },
  {
    _id: "644ef14398cd050002edc6e5",
    name: { common: "Saint Martin", official: "Saint Martin" },
    alpha2Code: "MF",
    alpha3Code: "MAF",
  },
  {
    _id: "644ef14398cd050002edc6e4",
    name: {
      common: "Macau",
      official:
        "Macao Special Administrative Region of the People's Republic of China",
    },
    alpha2Code: "MO",
    alpha3Code: "MAC",
  },
  {
    _id: "644ef14398cd050002edc6e2",
    name: { common: "Luxembourg", official: "Grand Duchy of Luxembourg" },
    alpha2Code: "LU",
    alpha3Code: "LUX",
  },
  {
    _id: "644ef14398cd050002edc6e1",
    name: { common: "Lithuania", official: "Republic of Lithuania" },
    alpha2Code: "LT",
    alpha3Code: "LTU",
  },
  {
    _id: "644ef14398cd050002edc6e3",
    name: { common: "Latvia", official: "Republic of Latvia" },
    alpha2Code: "LV",
    alpha3Code: "LVA",
  },
  {
    _id: "644ef14398cd050002edc6e6",
    name: { common: "Morocco", official: "Kingdom of Morocco" },
    alpha2Code: "MA",
    alpha3Code: "MAR",
  },
  {
    _id: "644ef14398cd050002edc6e8",
    name: { common: "Moldova", official: "Republic of Moldova" },
    alpha2Code: "MD",
    alpha3Code: "MDA",
  },
  {
    _id: "644ef14398cd050002edc6e7",
    name: { common: "Monaco", official: "Principality of Monaco" },
    alpha2Code: "MC",
    alpha3Code: "MCO",
  },
  {
    _id: "644ef14398cd050002edc6e9",
    name: { common: "Madagascar", official: "Republic of Madagascar" },
    alpha2Code: "MG",
    alpha3Code: "MDG",
  },
  {
    _id: "644ef14398cd050002edc6ea",
    name: { common: "Maldives", official: "Republic of the Maldives" },
    alpha2Code: "MV",
    alpha3Code: "MDV",
  },
  {
    _id: "644ef14398cd050002edc6eb",
    name: { common: "Mexico", official: "United Mexican States" },
    alpha2Code: "MX",
    alpha3Code: "MEX",
  },
  {
    _id: "644ef14398cd050002edc6f5",
    name: {
      common: "Mauritania",
      official: "Islamic Republic of Mauritania",
    },
    alpha2Code: "MR",
    alpha3Code: "MRT",
  },
  {
    _id: "644ef14398cd050002edc6f0",
    name: {
      common: "Myanmar",
      official: "Republic of the Union of Myanmar",
    },
    alpha2Code: "MM",
    alpha3Code: "MMR",
  },
  {
    _id: "644ef14398cd050002edc6f1",
    name: { common: "Montenegro", official: "Montenegro" },
    alpha2Code: "ME",
    alpha3Code: "MNE",
  },
  {
    _id: "644ef14398cd050002edc6f4",
    name: { common: "Mozambique", official: "Republic of Mozambique" },
    alpha2Code: "MZ",
    alpha3Code: "MOZ",
  },
  {
    _id: "644ef14398cd050002edc6ed",
    name: {
      common: "North Macedonia",
      official: "Republic of North Macedonia",
    },
    alpha2Code: "MK",
    alpha3Code: "MKD",
  },
  {
    _id: "644ef14398cd050002edc6f2",
    name: { common: "Mongolia", official: "Mongolia" },
    alpha2Code: "MN",
    alpha3Code: "MNG",
  },
  {
    _id: "644ef14398cd050002edc6ef",
    name: { common: "Malta", official: "Republic of Malta" },
    alpha2Code: "MT",
    alpha3Code: "MLT",
  },
  {
    _id: "644ef14398cd050002edc6f3",
    name: {
      common: "Northern Mariana Islands",
      official: "Commonwealth of the Northern Mariana Islands",
    },
    alpha2Code: "MP",
    alpha3Code: "MNP",
  },
  {
    _id: "644ef14398cd050002edc6ee",
    name: { common: "Mali", official: "Republic of Mali" },
    alpha2Code: "ML",
    alpha3Code: "MLI",
  },
  {
    _id: "644ef14398cd050002edc6ec",
    name: {
      common: "Marshall Islands",
      official: "Republic of the Marshall Islands",
    },
    alpha2Code: "MH",
    alpha3Code: "MHL",
  },
  {
    _id: "644ef14398cd050002edc6f6",
    name: { common: "Montserrat", official: "Montserrat" },
    alpha2Code: "MS",
    alpha3Code: "MSR",
  },
  {
    _id: "644ef14398cd050002edc6f7",
    name: { common: "Martinique", official: "Martinique" },
    alpha2Code: "MQ",
    alpha3Code: "MTQ",
  },
  {
    _id: "644ef14398cd050002edc6fc",
    name: { common: "Namibia", official: "Republic of Namibia" },
    alpha2Code: "NA",
    alpha3Code: "NAM",
  },
  {
    _id: "644ef14398cd050002edc6fb",
    name: { common: "Mayotte", official: "Department of Mayotte" },
    alpha2Code: "YT",
    alpha3Code: "MYT",
  },
  {
    _id: "644ef14398cd050002edc6ff",
    name: {
      common: "Norfolk Island",
      official: "Territory of Norfolk Island",
    },
    alpha2Code: "NF",
    alpha3Code: "NFK",
  },
  {
    _id: "644ef14398cd050002edc6f8",
    name: { common: "Mauritius", official: "Republic of Mauritius" },
    alpha2Code: "MU",
    alpha3Code: "MUS",
  },
  {
    _id: "644ef14398cd050002edc6fa",
    name: { common: "Malaysia", official: "Malaysia" },
    alpha2Code: "MY",
    alpha3Code: "MYS",
  },
  {
    _id: "644ef14398cd050002edc6fe",
    name: { common: "Niger", official: "Republic of Niger" },
    alpha2Code: "NE",
    alpha3Code: "NER",
  },
  {
    _id: "644ef14398cd050002edc6fd",
    name: { common: "New Caledonia", official: "New Caledonia" },
    alpha2Code: "NC",
    alpha3Code: "NCL",
  },
  {
    _id: "644ef14398cd050002edc6f9",
    name: { common: "Malawi", official: "Republic of Malawi" },
    alpha2Code: "MW",
    alpha3Code: "MWI",
  },
  {
    _id: "644ef14398cd050002edc700",
    name: { common: "Nigeria", official: "Federal Republic of Nigeria" },
    alpha2Code: "NG",
    alpha3Code: "NGA",
  },
  {
    _id: "644ef14398cd050002edc6aa",
    name: { common: "Gabon", official: "Gabonese Republic" },
    alpha2Code: "GA",
    alpha3Code: "GAB",
  },
  {
    _id: "644ef14398cd050002edc6a9",
    name: {
      common: "Micronesia",
      official: "Federated States of Micronesia",
    },
    alpha2Code: "FM",
    alpha3Code: "FSM",
  },
  {
    _id: "644ef14398cd050002edc6ac",
    name: { common: "Georgia", official: "Georgia" },
    alpha2Code: "GE",
    alpha3Code: "GEO",
  },
  {
    _id: "644ef14398cd050002edc6ab",
    name: {
      common: "United Kingdom",
      official: "United Kingdom of Great Britain and Northern Ireland",
    },
    alpha2Code: "GB",
    alpha3Code: "GBR",
  },
  {
    _id: "644ef14398cd050002edc6ad",
    name: { common: "Guernsey", official: "Bailiwick of Guernsey" },
    alpha2Code: "GG",
    alpha3Code: "GGY",
  },
  {
    _id: "644ef14398cd050002edc6ae",
    name: { common: "Ghana", official: "Republic of Ghana" },
    alpha2Code: "GH",
    alpha3Code: "GHA",
  },
  {
    _id: "644ef14398cd050002edc6af",
    name: { common: "Gibraltar", official: "Gibraltar" },
    alpha2Code: "GI",
    alpha3Code: "GIB",
  },
  {
    _id: "644ef14398cd050002edc6b0",
    name: { common: "Guinea", official: "Republic of Guinea" },
    alpha2Code: "GN",
    alpha3Code: "GIN",
  },
  {
    _id: "644ef14398cd050002edc6b2",
    name: { common: "Gambia", official: "Republic of the Gambia" },
    alpha2Code: "GM",
    alpha3Code: "GMB",
  },
  {
    _id: "644ef14398cd050002edc6b1",
    name: { common: "Guadeloupe", official: "Guadeloupe" },
    alpha2Code: "GP",
    alpha3Code: "GLP",
  },
  {
    _id: "644ef14398cd050002edc6b3",
    name: {
      common: "Guinea-Bissau",
      official: "Republic of Guinea-Bissau",
    },
    alpha2Code: "GW",
    alpha3Code: "GNB",
  },
  {
    _id: "644ef14398cd050002edc6b4",
    name: {
      common: "Equatorial Guinea",
      official: "Republic of Equatorial Guinea",
    },
    alpha2Code: "GQ",
    alpha3Code: "GNQ",
  },
  {
    _id: "644ef14398cd050002edc6b6",
    name: { common: "Grenada", official: "Grenada" },
    alpha2Code: "GD",
    alpha3Code: "GRD",
  },
  {
    _id: "644ef14398cd050002edc6b5",
    name: { common: "Greece", official: "Hellenic Republic" },
    alpha2Code: "GR",
    alpha3Code: "GRC",
  },
  {
    _id: "644ef14398cd050002edc6b7",
    name: { common: "Greenland", official: "Greenland" },
    alpha2Code: "GL",
    alpha3Code: "GRL",
  },
  {
    _id: "644ef14398cd050002edc6b8",
    name: { common: "Guatemala", official: "Republic of Guatemala" },
    alpha2Code: "GT",
    alpha3Code: "GTM",
  },
  {
    _id: "644ef14398cd050002edc6b9",
    name: { common: "French Guiana", official: "Guiana" },
    alpha2Code: "GF",
    alpha3Code: "GUF",
  },
  {
    _id: "644ef14398cd050002edc6ba",
    name: { common: "Guam", official: "Guam" },
    alpha2Code: "GU",
    alpha3Code: "GUM",
  },
  {
    _id: "644ef14398cd050002edc6bc",
    name: {
      common: "Hong Kong",
      official:
        "Hong Kong Special Administrative Region of the People's Republic of China",
    },
    alpha2Code: "HK",
    alpha3Code: "HKG",
  },
  {
    _id: "644ef14398cd050002edc6bb",
    name: {
      common: "Guyana",
      official: "Co-operative Republic of Guyana",
    },
    alpha2Code: "GY",
    alpha3Code: "GUY",
  },
  {
    _id: "644ef14398cd050002edc6bd",
    name: {
      common: "Heard Island and McDonald Islands",
      official: "Heard Island and McDonald Islands",
    },
    alpha2Code: "HM",
    alpha3Code: "HMD",
  },
  {
    _id: "644ef14398cd050002edc6be",
    name: { common: "Honduras", official: "Republic of Honduras" },
    alpha2Code: "HN",
    alpha3Code: "HND",
  },
  {
    _id: "644ef14398cd050002edc6c0",
    name: { common: "Haiti", official: "Republic of Haiti" },
    alpha2Code: "HT",
    alpha3Code: "HTI",
  },
  {
    _id: "644ef14398cd050002edc6bf",
    name: { common: "Croatia", official: "Republic of Croatia" },
    alpha2Code: "HR",
    alpha3Code: "HRV",
  },
  {
    _id: "644ef14398cd050002edc6c3",
    name: { common: "Isle of Man", official: "Isle of Man" },
    alpha2Code: "IM",
    alpha3Code: "IMN",
  },
  {
    _id: "644ef14398cd050002edc6c4",
    name: { common: "India", official: "Republic of India" },
    alpha2Code: "IN",
    alpha3Code: "IND",
  },
  {
    _id: "644ef14398cd050002edc6c2",
    name: { common: "Indonesia", official: "Republic of Indonesia" },
    alpha2Code: "ID",
    alpha3Code: "IDN",
  },
  {
    _id: "644ef14398cd050002edc6c5",
    name: {
      common: "British Indian Ocean Territory",
      official: "British Indian Ocean Territory",
    },
    alpha2Code: "IO",
    alpha3Code: "IOT",
  },
  {
    _id: "644ef14398cd050002edc6c1",
    name: { common: "Hungary", official: "Hungary" },
    alpha2Code: "HU",
    alpha3Code: "HUN",
  },
  {
    _id: "644ef14398cd050002edc6c6",
    name: { common: "Ireland", official: "Republic of Ireland" },
    alpha2Code: "IE",
    alpha3Code: "IRL",
  },
  {
    _id: "644ef14398cd050002edc6c7",
    name: { common: "Iran", official: "Islamic Republic of Iran" },
    alpha2Code: "IR",
    alpha3Code: "IRN",
  },
  {
    _id: "644ef14398cd050002edc6c8",
    name: { common: "Iraq", official: "Republic of Iraq" },
    alpha2Code: "IQ",
    alpha3Code: "IRQ",
  },
  {
    _id: "644ef14398cd050002edc6ca",
    name: { common: "Israel", official: "State of Israel" },
    alpha2Code: "IL",
    alpha3Code: "ISR",
  },
  {
    _id: "644ef14398cd050002edc6c9",
    name: { common: "Iceland", official: "Iceland" },
    alpha2Code: "IS",
    alpha3Code: "ISL",
  },
  {
    _id: "644ef14398cd050002edc6cb",
    name: { common: "Italy", official: "Italian Republic" },
    alpha2Code: "IT",
    alpha3Code: "ITA",
  },
  {
    _id: "644ef14398cd050002edc6cc",
    name: { common: "Jamaica", official: "Jamaica" },
    alpha2Code: "JM",
    alpha3Code: "JAM",
  },
  {
    _id: "644ef14398cd050002edc6d0",
    name: { common: "Kazakhstan", official: "Republic of Kazakhstan" },
    alpha2Code: "KZ",
    alpha3Code: "KAZ",
  },
  {
    _id: "644ef14398cd050002edc6cd",
    name: { common: "Jersey", official: "Bailiwick of Jersey" },
    alpha2Code: "JE",
    alpha3Code: "JEY",
  },
  {
    _id: "644ef14398cd050002edc6cf",
    name: { common: "Japan", official: "Japan" },
    alpha2Code: "JP",
    alpha3Code: "JPN",
  },
  {
    _id: "644ef14398cd050002edc6ce",
    name: { common: "Jordan", official: "Hashemite Kingdom of Jordan" },
    alpha2Code: "JO",
    alpha3Code: "JOR",
  },
  {
    _id: "644ef14398cd050002edc6d1",
    name: { common: "Kenya", official: "Republic of Kenya" },
    alpha2Code: "KE",
    alpha3Code: "KEN",
  },
  {
    _id: "644ef14398cd050002edc6d2",
    name: { common: "Kyrgyzstan", official: "Kyrgyz Republic" },
    alpha2Code: "KG",
    alpha3Code: "KGZ",
  },
  {
    _id: "644ef14398cd050002edc6d4",
    name: {
      common: "Kiribati",
      official: "Independent and Sovereign Republic of Kiribati",
    },
    alpha2Code: "KI",
    alpha3Code: "KIR",
  },
  {
    _id: "644ef14398cd050002edc6d3",
    name: { common: "Cambodia", official: "Kingdom of Cambodia" },
    alpha2Code: "KH",
    alpha3Code: "KHM",
  },
  {
    _id: "644ef14398cd050002edc6d5",
    name: {
      common: "Saint Kitts and Nevis",
      official: "Federation of Saint Christopher and Nevis",
    },
    alpha2Code: "KN",
    alpha3Code: "KNA",
  },
  {
    _id: "644ef14398cd050002edc6d6",
    name: { common: "South Korea", official: "Republic of Korea" },
    alpha2Code: "KR",
    alpha3Code: "KOR",
  },
  {
    _id: "644ef14398cd050002edc6d7",
    name: { common: "Kosovo", official: "Republic of Kosovo" },
    alpha2Code: "XK",
    alpha3Code: "UNK",
  },
  {
    _id: "644ef14398cd050002edc680",
    name: { common: "Bouvet Island", official: "Bouvet Island" },
    alpha2Code: "BV",
    alpha3Code: "BVT",
  },
  {
    _id: "644ef14398cd050002edc682",
    name: {
      common: "Central African Republic",
      official: "Central African Republic",
    },
    alpha2Code: "CF",
    alpha3Code: "CAF",
  },
  {
    _id: "644ef14398cd050002edc681",
    name: { common: "Botswana", official: "Republic of Botswana" },
    alpha2Code: "BW",
    alpha3Code: "BWA",
  },
  {
    _id: "644ef14398cd050002edc683",
    name: { common: "Canada", official: "Canada" },
    alpha2Code: "CA",
    alpha3Code: "CAN",
  },
  {
    _id: "644ef14398cd050002edc684",
    name: {
      common: "Cocos (Keeling) Islands",
      official: "Territory of the Cocos (Keeling) Islands",
    },
    alpha2Code: "CC",
    alpha3Code: "CCK",
  },
  {
    _id: "644ef14398cd050002edc685",
    name: { common: "Switzerland", official: "Swiss Confederation" },
    alpha2Code: "CH",
    alpha3Code: "CHE",
  },
  {
    _id: "644ef14398cd050002edc686",
    name: { common: "Chile", official: "Republic of Chile" },
    alpha2Code: "CL",
    alpha3Code: "CHL",
  },
  {
    _id: "644ef14398cd050002edc689",
    name: { common: "Cameroon", official: "Republic of Cameroon" },
    alpha2Code: "CM",
    alpha3Code: "CMR",
  },
  {
    _id: "644ef14398cd050002edc688",
    name: {
      common: "Ivory Coast",
      official: "Republic of Côte d'Ivoire",
    },
    alpha2Code: "CI",
    alpha3Code: "CIV",
  },
  {
    _id: "644ef14398cd050002edc687",
    name: { common: "China", official: "People's Republic of China" },
    alpha2Code: "CN",
    alpha3Code: "CHN",
  },
  {
    _id: "644ef14398cd050002edc68a",
    name: {
      common: "DR Congo",
      official: "Democratic Republic of the Congo",
    },
    alpha2Code: "CD",
    alpha3Code: "COD",
  },
  {
    _id: "644ef14398cd050002edc68c",
    name: { common: "Cook Islands", official: "Cook Islands" },
    alpha2Code: "CK",
    alpha3Code: "COK",
  },
  {
    _id: "644ef14398cd050002edc68b",
    name: {
      common: "Republic of the Congo",
      official: "Republic of the Congo",
    },
    alpha2Code: "CG",
    alpha3Code: "COG",
  },
  {
    _id: "644ef14398cd050002edc68e",
    name: { common: "Comoros", official: "Union of the Comoros" },
    alpha2Code: "KM",
    alpha3Code: "COM",
  },
  {
    _id: "644ef14398cd050002edc68d",
    name: { common: "Colombia", official: "Republic of Colombia" },
    alpha2Code: "CO",
    alpha3Code: "COL",
  },
  {
    _id: "644ef14398cd050002edc68f",
    name: { common: "Cape Verde", official: "Republic of Cabo Verde" },
    alpha2Code: "CV",
    alpha3Code: "CPV",
  },
  {
    _id: "644ef14398cd050002edc690",
    name: { common: "Costa Rica", official: "Republic of Costa Rica" },
    alpha2Code: "CR",
    alpha3Code: "CRI",
  },
  {
    _id: "644ef14398cd050002edc693",
    name: {
      common: "Christmas Island",
      official: "Territory of Christmas Island",
    },
    alpha2Code: "CX",
    alpha3Code: "CXR",
  },
  {
    _id: "644ef14398cd050002edc691",
    name: { common: "Cuba", official: "Republic of Cuba" },
    alpha2Code: "CU",
    alpha3Code: "CUB",
  },
  {
    _id: "644ef14398cd050002edc692",
    name: { common: "Curaçao", official: "Country of Curaçao" },
    alpha2Code: "CW",
    alpha3Code: "CUW",
  },
  {
    _id: "644ef14398cd050002edc694",
    name: { common: "Cayman Islands", official: "Cayman Islands" },
    alpha2Code: "KY",
    alpha3Code: "CYM",
  },
  {
    _id: "644ef14398cd050002edc695",
    name: { common: "Cyprus", official: "Republic of Cyprus" },
    alpha2Code: "CY",
    alpha3Code: "CYP",
  },
  {
    _id: "644ef14398cd050002edc696",
    name: { common: "Czechia", official: "Czech Republic" },
    alpha2Code: "CZ",
    alpha3Code: "CZE",
  },
  {
    _id: "644ef14398cd050002edc697",
    name: { common: "Germany", official: "Federal Republic of Germany" },
    alpha2Code: "DE",
    alpha3Code: "DEU",
  },
  {
    _id: "644ef14398cd050002edc699",
    name: { common: "Dominica", official: "Commonwealth of Dominica" },
    alpha2Code: "DM",
    alpha3Code: "DMA",
  },
  {
    _id: "644ef14398cd050002edc69a",
    name: { common: "Denmark", official: "Kingdom of Denmark" },
    alpha2Code: "DK",
    alpha3Code: "DNK",
  },
  {
    _id: "644ef14398cd050002edc698",
    name: { common: "Djibouti", official: "Republic of Djibouti" },
    alpha2Code: "DJ",
    alpha3Code: "DJI",
  },
  {
    _id: "644ef14398cd050002edc69b",
    name: {
      common: "Dominican Republic",
      official: "Dominican Republic",
    },
    alpha2Code: "DO",
    alpha3Code: "DOM",
  },
  {
    _id: "644ef14398cd050002edc69c",
    name: {
      common: "Algeria",
      official: "People's Democratic Republic of Algeria",
    },
    alpha2Code: "DZ",
    alpha3Code: "DZA",
  },
  {
    _id: "644ef14398cd050002edc69d",
    name: { common: "Ecuador", official: "Republic of Ecuador" },
    alpha2Code: "EC",
    alpha3Code: "ECU",
  },
  {
    _id: "644ef14398cd050002edc69e",
    name: { common: "Egypt", official: "Arab Republic of Egypt" },
    alpha2Code: "EG",
    alpha3Code: "EGY",
  },
  {
    _id: "644ef14398cd050002edc69f",
    name: { common: "Eritrea", official: "State of Eritrea" },
    alpha2Code: "ER",
    alpha3Code: "ERI",
  },
  {
    _id: "644ef14398cd050002edc6a0",
    name: {
      common: "Western Sahara",
      official: "Sahrawi Arab Democratic Republic",
    },
    alpha2Code: "EH",
    alpha3Code: "ESH",
  },
  {
    _id: "644ef14398cd050002edc6a1",
    name: { common: "Spain", official: "Kingdom of Spain" },
    alpha2Code: "ES",
    alpha3Code: "ESP",
  },
  {
    _id: "644ef14398cd050002edc6a2",
    name: { common: "Estonia", official: "Republic of Estonia" },
    alpha2Code: "EE",
    alpha3Code: "EST",
  },
  {
    _id: "644ef14398cd050002edc6a4",
    name: { common: "Finland", official: "Republic of Finland" },
    alpha2Code: "FI",
    alpha3Code: "FIN",
  },
  {
    _id: "644ef14398cd050002edc6a3",
    name: {
      common: "Ethiopia",
      official: "Federal Democratic Republic of Ethiopia",
    },
    alpha2Code: "ET",
    alpha3Code: "ETH",
  },
  {
    _id: "644ef14398cd050002edc6a7",
    name: { common: "France", official: "French Republic" },
    alpha2Code: "FR",
    alpha3Code: "FRA",
  },
  {
    _id: "644ef14398cd050002edc6a5",
    name: { common: "Fiji", official: "Republic of Fiji" },
    alpha2Code: "FJ",
    alpha3Code: "FJI",
  },
  {
    _id: "644ef14398cd050002edc6a8",
    name: { common: "Faroe Islands", official: "Faroe Islands" },
    alpha2Code: "FO",
    alpha3Code: "FRO",
  },
  {
    _id: "644ef14398cd050002edc6a6",
    name: { common: "Falkland Islands", official: "Falkland Islands" },
    alpha2Code: "FK",
    alpha3Code: "FLK",
  },
  {
    _id: "644ef14398cd050002edc65d",
    name: { common: "Angola", official: "Republic of Angola" },
    alpha2Code: "AO",
    alpha3Code: "AGO",
  },
  {
    _id: "644ef14398cd050002edc65e",
    name: { common: "Anguilla", official: "Anguilla" },
    alpha2Code: "AI",
    alpha3Code: "AIA",
  },
  {
    _id: "644ef14398cd050002edc663",
    name: { common: "Argentina", official: "Argentine Republic" },
    alpha2Code: "AR",
    alpha3Code: "ARG",
  },
  {
    _id: "644ef14398cd050002edc661",
    name: { common: "Andorra", official: "Principality of Andorra" },
    alpha2Code: "AD",
    alpha3Code: "AND",
  },
  {
    _id: "644ef14398cd050002edc65f",
    name: { common: "Åland Islands", official: "Åland Islands" },
    alpha2Code: "AX",
    alpha3Code: "ALA",
  },
  {
    _id: "644ef14398cd050002edc662",
    name: {
      common: "United Arab Emirates",
      official: "United Arab Emirates",
    },
    alpha2Code: "AE",
    alpha3Code: "ARE",
  },
  {
    _id: "644ef14398cd050002edc664",
    name: { common: "Armenia", official: "Republic of Armenia" },
    alpha2Code: "AM",
    alpha3Code: "ARM",
  },
  {
    _id: "644ef14398cd050002edc665",
    name: { common: "American Samoa", official: "American Samoa" },
    alpha2Code: "AS",
    alpha3Code: "ASM",
  },
  {
    _id: "644ef14398cd050002edc666",
    name: { common: "Antarctica", official: "Antarctica" },
    alpha2Code: "AQ",
    alpha3Code: "ATA",
  },
  {
    _id: "644ef14398cd050002edc660",
    name: { common: "Albania", official: "Republic of Albania" },
    alpha2Code: "AL",
    alpha3Code: "ALB",
  },
  {
    _id: "644ef14398cd050002edc668",
    name: {
      common: "Antigua and Barbuda",
      official: "Antigua and Barbuda",
    },
    alpha2Code: "AG",
    alpha3Code: "ATG",
  },
  {
    _id: "644ef14398cd050002edc667",
    name: {
      common: "French Southern and Antarctic Lands",
      official: "Territory of the French Southern and Antarctic Lands",
    },
    alpha2Code: "TF",
    alpha3Code: "ATF",
  },
  {
    _id: "644ef14398cd050002edc669",
    name: { common: "Australia", official: "Commonwealth of Australia" },
    alpha2Code: "AU",
    alpha3Code: "AUS",
  },
  {
    _id: "644ef14398cd050002edc66a",
    name: { common: "Austria", official: "Republic of Austria" },
    alpha2Code: "AT",
    alpha3Code: "AUT",
  },
  {
    _id: "644ef14398cd050002edc66e",
    name: { common: "Benin", official: "Republic of Benin" },
    alpha2Code: "BJ",
    alpha3Code: "BEN",
  },
  {
    _id: "644ef14398cd050002edc66b",
    name: { common: "Azerbaijan", official: "Republic of Azerbaijan" },
    alpha2Code: "AZ",
    alpha3Code: "AZE",
  },
  {
    _id: "644ef14398cd050002edc66c",
    name: { common: "Burundi", official: "Republic of Burundi" },
    alpha2Code: "BI",
    alpha3Code: "BDI",
  },
  {
    _id: "644ef14398cd050002edc66f",
    name: { common: "Burkina Faso", official: "Burkina Faso" },
    alpha2Code: "BF",
    alpha3Code: "BFA",
  },
  {
    _id: "644ef14398cd050002edc670",
    name: {
      common: "Bangladesh",
      official: "People's Republic of Bangladesh",
    },
    alpha2Code: "BD",
    alpha3Code: "BGD",
  },
  {
    _id: "644ef14398cd050002edc66d",
    name: { common: "Belgium", official: "Kingdom of Belgium" },
    alpha2Code: "BE",
    alpha3Code: "BEL",
  },
  {
    _id: "644ef14398cd050002edc671",
    name: { common: "Bulgaria", official: "Republic of Bulgaria" },
    alpha2Code: "BG",
    alpha3Code: "BGR",
  },
  {
    _id: "644ef14398cd050002edc672",
    name: { common: "Bahrain", official: "Kingdom of Bahrain" },
    alpha2Code: "BH",
    alpha3Code: "BHR",
  },
  {
    _id: "644ef14398cd050002edc674",
    name: {
      common: "Bosnia and Herzegovina",
      official: "Bosnia and Herzegovina",
    },
    alpha2Code: "BA",
    alpha3Code: "BIH",
  },
  {
    _id: "644ef14398cd050002edc673",
    name: { common: "Bahamas", official: "Commonwealth of the Bahamas" },
    alpha2Code: "BS",
    alpha3Code: "BHS",
  },
  {
    _id: "644ef14398cd050002edc675",
    name: {
      common: "Saint Barthélemy",
      official: "Collectivity of Saint Barthélemy",
    },
    alpha2Code: "BL",
    alpha3Code: "BLM",
  },
  {
    _id: "644ef14398cd050002edc676",
    name: {
      common: "Saint Helena, Ascension and Tristan da Cunha",
      official: "Saint Helena, Ascension and Tristan da Cunha",
    },
    alpha2Code: "SH",
    alpha3Code: "SHN",
  },
  {
    _id: "644ef14398cd050002edc677",
    name: { common: "Belarus", official: "Republic of Belarus" },
    alpha2Code: "BY",
    alpha3Code: "BLR",
  },
  {
    _id: "644ef14398cd050002edc67a",
    name: {
      common: "Bolivia",
      official: "Plurinational State of Bolivia",
    },
    alpha2Code: "BO",
    alpha3Code: "BOL",
  },
  {
    _id: "644ef14398cd050002edc679",
    name: { common: "Bermuda", official: "Bermuda" },
    alpha2Code: "BM",
    alpha3Code: "BMU",
  },
  {
    _id: "644ef14398cd050002edc678",
    name: { common: "Belize", official: "Belize" },
    alpha2Code: "BZ",
    alpha3Code: "BLZ",
  },
  {
    _id: "644ef14398cd050002edc67d",
    name: { common: "Barbados", official: "Barbados" },
    alpha2Code: "BB",
    alpha3Code: "BRB",
  },
  {
    _id: "644ef14398cd050002edc67b",
    name: {
      common: "Caribbean Netherlands",
      official: "Bonaire, Sint Eustatius and Saba",
    },
    alpha2Code: "BQ",
    alpha3Code: "BES",
  },
  {
    _id: "644ef14398cd050002edc67e",
    name: {
      common: "Brunei",
      official: "Nation of Brunei, Abode of Peace",
    },
    alpha2Code: "BN",
    alpha3Code: "BRN",
  },
  {
    _id: "644ef14398cd050002edc67c",
    name: { common: "Brazil", official: "Federative Republic of Brazil" },
    alpha2Code: "BR",
    alpha3Code: "BRA",
  },
  {
    _id: "644ef14398cd050002edc67f",
    name: { common: "Bhutan", official: "Kingdom of Bhutan" },
    alpha2Code: "BT",
    alpha3Code: "BTN",
  },
  {
    _id: "644ef14398cd050002edc65b",
    name: { common: "Aruba", official: "Aruba" },
    alpha2Code: "AW",
    alpha3Code: "ABW",
  },
  {
    _id: "644ef14398cd050002edc65c",
    name: {
      common: "Afghanistan",
      official: "Islamic Republic of Afghanistan",
    },
    alpha2Code: "AF",
    alpha3Code: "AFG",
  },
];
